name-template: v$NEXT_PATCH_VERSION
tag-template: v$NEXT_PATCH_VERSION
template: |
  # What's Changed

  $CHANGES
categories:
  - title: Features
    labels:
      - feature
      - enhancement

  - title: Bug Fixes
    labels:
      - fix
      - bug

  - title: Documentation
    labels:
      - documentation
      - docs

  - title: Maintenance
    labels:
      - maintenance
      - refactor
      - build
      - test
